# Generated by Django 4.2.9 on 2024-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_chat_remove_message_chat_id_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
